name: Node.js CI/CD

on:
  push:
    branches: [ feature, develop ]
  pull_request:
    branches: [ main]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build Docker Image
      run: docker build -t qurrordoc/mrco:latest . && docker image prune -f
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Push the Docker image to the Docker Hub
      run: docker push qurrordoc/mrco:latest
    - name: End build the Docker image
      run: echo "Docker image created succesfully!"
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Preparation and cleanup for deploy
        run:  docker rm -f $(docker ps -a -q) || echo "No containers available for cleaning"
      - name: Deploy the Docker image
        run: docker run -d -p 8080:8080 qurrordoc/mrco:latest
